# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a072f43e5533426ca97e11dde86cf367492b4389925ddf2147acb978b364d2af59c89300c594d988d69fd560bd36ef26f4056c4847b0ea8f93f26a5403f461c6
  google_auth:
    client_id: 225768126113-gm3fi8hpiei68kbadkg1nlsjsqnt1i4k.apps.googleusercontent.com
    client_secret: 2IiG3A5C1qeb-ylVPTfGZwHJ

test:
  secret_key_base: 8b4fb7b410ffc7a868f3225b55d4e9082b1ed8d15ae0c0c88d2806a305582717057e37263378969b1d1ecb2502d67cbc6f23c8e92e91eb437dbed33a7e4a689b
  google_auth:
    client_id: test
    client_secret: test

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_auth:
      client_id: <%= ENV["SECRET_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["SECRET_GOOGLE_CLIENT_SECRET"] %>
